### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by cAyou66** [Broxxar/NoMansScanner#1]
Hi there !
I really love your effect, but I would like to know if it's possible to add some control over which objects will "receive" the effect, by layer or tag or even script.
It would be great in my case, thanks !

**Comment by Broxxar** [comment]
That would be quite different. Instead of implementing this as an image effect, you would instead have a shader meant for use on a material that you place on an object. Say, an edit of the Standard PBR shader. You would include the world space distance calculation and color generation in that. Then you could set up the ScannerPosition and Time as shader Globals so that all objects using the material are consistent.

When you're working per object, getting the world space position is much easier, you can just perform a `mul` the input vertex with `_Object2World` in the vertex shader and pass that along to the fragment as a texcoord interpolator.

**Comment by cAyou66** [comment]
I was afraid I had to do that per object, using a shader. I remember using a post effect doing an outline per object and it was a post effect. But my guess is that the post effect is done by using different cameras with different culling masks. It's not ideal in terms of performances...
Anyway thanks for you reply, I will keep the effect like that :)
